title: APIs
description: This is for managing APIs used as part of intelligence

image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png

#url: /explore
url: /

email: kin@postman.com

github_user: postman-open-technologies
github_repo: intelligence
github_branch: main

version:      1.1.1
markdown:     kramdown

token: token

apis_base_url: https://umy5jz66lk.execute-api.us-west-1.amazonaws.com/staging