
name: Intelligence  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /github/search post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubsearch-po.zip github/search/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubsearch-po
            zip_file: m-s-githubsearch-po.zip
      - name: /github/harvest get lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubharvest-g.zip github/harvest/get/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubharvest-g
            zip_file: m-s-githubharvest-g.zip
      - name: /github/harvest post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubharvest-po.zip github/harvest/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubharvest-po
            zip_file: m-s-githubharvest-po.zip
      - name: /github/file get lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubfile-g.zip github/file/get/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubfile-g
            zip_file: m-s-githubfile-g.zip
      - name: /github/file post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubfile-po.zip github/file/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubfile-po
            zip_file: m-s-githubfile-po.zip            
      - name: /github/meta get lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubmeta-g.zip github/meta/get/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubmeta-g
            zip_file: m-s-githubmeta-g.zip
      - name: /github/meta post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubmeta-po.zip github/meta/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubmeta-po
            zip_file: m-s-githubmeta-po.zip
      - name: /github/validate get lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubvalidate-g.zip github/validate/get/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubvalidate-g
            zip_file: m-s-githubvalidate-g.zip
      - name: /github/validate post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-githubvalidate-po.zip github/validate/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-githubvalidate-po
            zip_file: m-s-githubvalidate-po.zip

      - name: /web/search post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-websearch-po.zip web/search/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-websearch-po
            zip_file: m-s-websearch-po.zip    
      - name: /web/harvest get lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-webharvest-g.zip web/harvest/get/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-webharvest-g
            zip_file: m-s-webharvest-g.zip
      - name: /web/harvest post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-webharvest-po.zip web/harvest/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-webharvest-po
            zip_file: m-s-webharvest-po.zip                    

      - name: /web/pull get lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-webpull-g.zip web/pull/get/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-webpull-g
            zip_file: m-s-webpull-g.zip
      - name: /web/pull post lambda deploy zip
        uses: postman-open-technologies/intelligence@main
        with:
            args: zip -qq -r m-s-webpull-po.zip web/pull/post/index.js node_modules
      - name: intelligence get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-webpull-po
            zip_file: m-s-webpull-po.zip             